name = "OccultEyes Create Modpack"
author = "ulv"
version = "0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e44e5c9aa25bdde3a9c1de343c05f27b5e25b386f647a051d5fecbc406f6741d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"
