name = "OccultEyes Create Modpack"
author = "ulv"
version = "0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8e3e8eb14ab95bdf2404b630c1cd4e0f8b9dab2ea75e76ce03d884932df056f1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"
