name = "OccultEyes Create Modpack"
author = "ulv"
version = "0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1fb3251198f0967cc768aaf6ee6357649bcb95e1868f8d480f32dfeae0cd772d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"
